eureka:
  client:
    service-url: # Eureka Server注册中心的地址, 用于Client与Server进行交流
      defaultZone: http://localhost:8100/eureka/

spring:
  application:
    name: user-service


server:
  port: 8120

management:
  endpoints:
    web:
      exposure:
        include: "*"

