eureka:
  client:
    service-url: # Eureka Server注册中心的地址, 用于Client与Server进行交流
      defaultZone: http://service-discovery:8100/eureka/

spring:
  application:
    name: cloud-gateway
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#            - POST
#            - DELETE
#            - OPTIONS

server:
  port: 8120

management:
  endpoints:
    web:
      exposure:
        include: "*"



